### PR TITLE
Implement a case-related activity change trigger

### PR DESCRIPTION
**Pull request by flaviovs**
This patch implements a case-related activity change trigger, to allow workflows based on activities that are related to cases.

Notice that this new trigger leverages the Activity trigger class by inheriting it.

### CODE REVIEW

**Comment by jaapjansma** [comment]
@flaviovs thanks for your PR it looks really good. Could you also supply an upgrader function to install the new trigger in existing installations?

**Comment by flaviovs** [comment]
@jaapjansma, sure I can do it. Will try to address this ASAP so that we can close the PR.

**Comment by flaviovs** [comment]
Ok, here it goes, the upgrade function.

**Comment by jaapjansma** [comment]
@flaviovs thanks. I have merged your PR's.

**Pull request merged**
