### PR TITLE
Fix relationship trigger

### PR DESCRIPTION
**Pull request by systopia**
Relationship based trigger wasn't working, due to some confusion with ``contact_id``. This should fix it.

### CODE REVIEW

**Comment by jaapjansma** [comment]
@systopia not sure whether this the way to go. You are assuming we are using contact_id_a of a relationship. But what if we want to use contact_id_b? So I would rather use a trigger on relationships firing for both contact_a and contact_b and then use a condition to determine whether it is contact a or contact b or whether you don't care. 

I thought I did fix this a while a go by using a different trigger class for relationships. But it might be that I only fixed the case role triggers.

**Comment by systopia** [comment]
You're right. But this patch wasn't supposed to fix the logical problem, but rather just make it work. Feel free to create a new ticket to address it. But I suggest merging this, so at least it doesn't crash any more.

**Comment by jaapjansma** [comment]
I am not sure about merging it. I would rather fix it in the right way. So either you could fix it logically or I will do it whenever I have time. 
If I am going to merge it I might forget about the logical problem and users might start to think that relationship triggers are working....

**Comment by systopia** [comment]
> If I am going to merge it I might forget about the logical problem

Well, that's why I suggested to create an issue. I'm not going to fix that logical problem now, because our client doesn't need it - as @ErikHommel repeatedly said on CiviCon Woerden: "Scratch your own itch". 

I personally think the triggers working while lacking the second contact dimension is better than them not working at all. Using ``contact_a`` as *the* contact ID isn't wrong, it's just not the full potential.

Plus, I wouldn't like to maintain a fork of CiviRules until somebody eventually comes up with a solution.

**Comment by jaapjansma** [comment]
@systopia okay. We will go for the short win.

**Comment by jaapjansma** [comment]
I have also created an issue for this: https://github.com/CiviCooP/org.civicoop.civirules/issues/83

**Pull request merged**
