### PR TITLE
Manual triggers

### PR DESCRIPTION
**Pull request by PalanteJon**
Hi Jaap and Erik,

I'm currently writing an extension called "Fast Action Links".  Like CiviRules, it's intended to solve a wide range of workflow issues.   It injects links into your search results that can execute arbitrary actions.  For instance, in the screenshot below, I've added "Accept" and "Reject" links next to each contact.  By clicking the link, you can add someone to an "Accepted" group or a "Rejected" group with a single click.
selection_117

I've just finished writing CiviRules integration - so clicking a link can now fire a CiviRule on the contact in question.  To make that work, I added a new trigger type (besides "Cron" and "Post") called "Manual".  To fire a CiviRule manually, you call a method with this signature: `CRM_Civirules_Trigger_Manual::process($ruleId, $objectId, $objectName)`.

I've just finished testing - on "Contact" entity type only, since my extension only supports contacts at the moment.  However, everything seems to work well - conditions, actions, etc.

### CODE REVIEW

**Comment by jaapjansma** [comment]
@PalanteJon thanks sounds like a really nice extension. Did you know that you could have your own triggers in your extension?  I do think that is a better solution than providing in the civirules code for all kind of custom extensions. 
We have an example in nl.pum.civirules (https://github.com/PUMNL/nl.pum.pumcivirules)

**Comment by PalanteJon** [comment]
@jaapjansma I hadn't really considered that approach, but I can see the advantage from the perspective of not adding code for you to maintain.  I'll rework this and see where it gets me.

**Comment by PalanteJon** [comment]
@jaapjansma Thank you for the suggestion!  I was able to get my trigger working with an unmodified version of Civirules.

**Comment by jaapjansma** [comment]
@PalanteJon great!

**Pull request closed without merging**
